/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.telas;

import java.sql.*;
import br.com.connection.ModuloConexao;
import java.text.DecimalFormat;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Home
 */
public class TelaEspeciais extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    DecimalFormat df = new DecimalFormat("#####.##");
    
    public TelaEspeciais() {
        initComponents();
        conexao = ModuloConexao.conector();
    }
    // variáveis de seleção
    public static String descricao, divi, ocupacaoEsp;
    public static double cargadeincendio;
    
    double  pce1, pce2, pce3, pce4, pce5,
            mass1, mass2, mass3, mass4, mass5,
            area, cargatotal;

    public static String getDivi() {
        return divi;
    }

    public static void setDivi(String divi) {
        TelaEspeciais.divi = divi;
    }

    public static String getOcupacaoEsp() {
        return ocupacaoEsp;
    }

    public static void setOcupacaoEsp(String ocupacaoEsp) {
        TelaEspeciais.ocupacaoEsp = ocupacaoEsp;
    }

    public static double getCargadeincendio() {
        return cargadeincendio;
    }

    public static void setCargadeincendio(double cargadeincendio) {
        TelaEspeciais.cargadeincendio = cargadeincendio;
    }
    
    
    
    // método para setar a descrição
    public void campoTexto(){
        txpDescrcao.setText(descricao);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterial = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txpDescrcao = new javax.swing.JTextPane();
        cbDivisao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        rbtn1 = new javax.swing.JRadioButton();
        rbtn2 = new javax.swing.JRadioButton();
        rbtn3 = new javax.swing.JRadioButton();
        rbtn4 = new javax.swing.JRadioButton();
        rbtn5 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtMat1 = new javax.swing.JTextField();
        txtMat2 = new javax.swing.JTextField();
        txtMat3 = new javax.swing.JTextField();
        txtMat4 = new javax.swing.JTextField();
        txtMat5 = new javax.swing.JTextField();
        txtMassa1 = new javax.swing.JTextField();
        txtMassa2 = new javax.swing.JTextField();
        txtMassa3 = new javax.swing.JTextField();
        txtMassa4 = new javax.swing.JTextField();
        txtMassa5 = new javax.swing.JTextField();
        txtPce1 = new javax.swing.JTextField();
        txtPce2 = new javax.swing.JTextField();
        txtPce3 = new javax.swing.JTextField();
        txtPce4 = new javax.swing.JTextField();
        txtPce5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtCargaTotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtOcupacao = new javax.swing.JTextField();
        txtDivisao = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 153, 255));
        setClosable(true);
        setForeground(new java.awt.Color(153, 153, 255));
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(900, 775));

        tblMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMaterial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaterialMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterial);

        txpDescrcao.setEditable(false);
        jScrollPane2.setViewportView(txpDescrcao);

        cbDivisao.setBackground(new java.awt.Color(51, 153, 255));
        cbDivisao.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        cbDivisao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Explosivos (Comércio)", "Explosivos (Indústria)", "Explosivos (Depósitos)", "Especiais (Centrais de comunicação)", "Especiais (Armazenamento e beneficiamento)" }));
        cbDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDivisaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel1.setText("Selecione a divisão e leia a descrição ao lado:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel2.setText("Pesquisar:");

        txtPesquisa.setBackground(new java.awt.Color(153, 255, 153));
        txtPesquisa.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtPesquisa.setToolTipText("Digite o tipo de material desejado.");
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        rbtn1.setBackground(new java.awt.Color(0, 102, 255));
        buttonGroup1.add(rbtn1);
        rbtn1.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        rbtn1.setText("1");

        buttonGroup1.add(rbtn2);
        rbtn2.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        rbtn2.setText("2");

        buttonGroup1.add(rbtn3);
        rbtn3.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        rbtn3.setText("3");

        buttonGroup1.add(rbtn4);
        rbtn4.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        rbtn4.setText("4");

        buttonGroup1.add(rbtn5);
        rbtn5.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        rbtn5.setText("5");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel3.setText("Área total do piso do pavimento (m²):");

        txtMat1.setEditable(false);
        txtMat1.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMat1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtMat2.setEditable(false);
        txtMat2.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMat2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtMat3.setEditable(false);
        txtMat3.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMat3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMat3.setPreferredSize(new java.awt.Dimension(170, 28));

        txtMat4.setEditable(false);
        txtMat4.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMat4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMat4.setPreferredSize(new java.awt.Dimension(170, 28));

        txtMat5.setEditable(false);
        txtMat5.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMat5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMat5.setPreferredSize(new java.awt.Dimension(170, 28));

        txtMassa1.setBackground(new java.awt.Color(51, 153, 255));
        txtMassa1.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMassa1.setText("0");
        txtMassa1.setPreferredSize(new java.awt.Dimension(70, 28));

        txtMassa2.setBackground(new java.awt.Color(51, 153, 255));
        txtMassa2.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMassa2.setText("0");
        txtMassa2.setPreferredSize(new java.awt.Dimension(70, 28));

        txtMassa3.setBackground(new java.awt.Color(51, 153, 255));
        txtMassa3.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMassa3.setText("0");
        txtMassa3.setPreferredSize(new java.awt.Dimension(70, 28));

        txtMassa4.setBackground(new java.awt.Color(51, 153, 255));
        txtMassa4.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMassa4.setText("0");
        txtMassa4.setPreferredSize(new java.awt.Dimension(70, 28));

        txtMassa5.setBackground(new java.awt.Color(51, 153, 255));
        txtMassa5.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtMassa5.setText("0");
        txtMassa5.setPreferredSize(new java.awt.Dimension(70, 28));

        txtPce1.setEditable(false);
        txtPce1.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtPce1.setText("0");
        txtPce1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPce1.setPreferredSize(new java.awt.Dimension(50, 28));

        txtPce2.setEditable(false);
        txtPce2.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtPce2.setText("0");
        txtPce2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPce2.setPreferredSize(new java.awt.Dimension(50, 28));

        txtPce3.setEditable(false);
        txtPce3.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtPce3.setText("0");
        txtPce3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPce3.setPreferredSize(new java.awt.Dimension(50, 28));

        txtPce4.setEditable(false);
        txtPce4.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtPce4.setText("0");
        txtPce4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPce4.setPreferredSize(new java.awt.Dimension(50, 28));

        txtPce5.setEditable(false);
        txtPce5.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtPce5.setText("0");
        txtPce5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPce5.setPreferredSize(new java.awt.Dimension(50, 28));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel4.setText("Material");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel5.setText("PCE (MJ/kg)");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel6.setText("Massa (Kg)");

        txtArea.setBackground(new java.awt.Color(51, 153, 255));
        txtArea.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtArea.setToolTipText("Área do piso que contém material.");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCargaTotal.setEditable(false);
        txtCargaTotal.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtCargaTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel7.setText("Carga de Incêndio MJ/M²:");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel8.setText("Ocupação:");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        jLabel9.setText("Divisão:");

        txtOcupacao.setEditable(false);
        txtOcupacao.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtOcupacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtDivisao.setEditable(false);
        txtDivisao.setFont(new java.awt.Font("sansserif", 0, 11)); // NOI18N
        txtDivisao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(31, 31, 31)
                                                .addComponent(txtCargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addComponent(jLabel8)
                                                .addGap(31, 31, 31)
                                                .addComponent(txtOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(jLabel9)
                                                .addGap(31, 31, 31)
                                                .addComponent(txtDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jButton1)
                                .addGap(35, 35, 35)
                                .addComponent(jButton2)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbtn1)
                            .addComponent(rbtn2)
                            .addComponent(rbtn3)
                            .addComponent(rbtn4)
                            .addComponent(rbtn5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(txtPce1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(txtMassa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(cbDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMat5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPce5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMassa5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOcupacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addGap(0, 364, Short.MAX_VALUE))
        );

        setBounds(0, 0, 900, 650);
    }// </editor-fold>//GEN-END:initComponents

    // método para calcular a carga total
    public void calcular(){
        pce1 = Double.parseDouble(txtPce1.getText());
        pce2 = Double.parseDouble(txtPce2.getText());
        pce3 = Double.parseDouble(txtPce3.getText());
        pce4 = Double.parseDouble(txtPce4.getText());
        pce5 = Double.parseDouble(txtPce5.getText());
        mass1 = Double.parseDouble(txtMassa1.getText().replaceAll(",", "."));
        mass2 = Double.parseDouble(txtMassa2.getText().replaceAll(",", "."));
        mass3 = Double.parseDouble(txtMassa3.getText().replaceAll(",", "."));
        mass4 = Double.parseDouble(txtMassa4.getText().replaceAll(",", "."));
        mass5 = Double.parseDouble(txtMassa5.getText().replaceAll(",", "."));
        area = Double.parseDouble(txtArea.getText().replaceAll(",", "."));
        
        cargatotal = ((pce1*mass1)+(pce2*mass2)+(pce3*mass3)+(pce4*mass4)+(pce5*mass5))/area;
        
        txtCargaTotal.setText(String.valueOf(df.format(cargatotal)));
        cargadeincendio = cargatotal;
        
    }
    
    // método de pesquisa do material
    public void pesquisar(){
        String sql = "select material, podercalorifico from materiais where material like ?";
        try {
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txtPesquisa.getText() + "%");
            rs = pst.executeQuery();
            tblMaterial.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
    // método para setar os campos
    public void setar(){
        int setar = tblMaterial.getSelectedRow();
        if (rbtn1.isSelected()){
            txtMat1.setText(tblMaterial.getModel().getValueAt(setar, 0).toString());
            txtPce1.setText(tblMaterial.getModel().getValueAt(setar, 1).toString());
        } else if (rbtn2.isSelected()){
            txtMat2.setText(tblMaterial.getModel().getValueAt(setar, 0).toString());
            txtPce2.setText(tblMaterial.getModel().getValueAt(setar, 1).toString());
        }else if (rbtn3.isSelected()){
            txtMat3.setText(tblMaterial.getModel().getValueAt(setar, 0).toString());
            txtPce3.setText(tblMaterial.getModel().getValueAt(setar, 1).toString());
        }else if (rbtn4.isSelected()){
            txtMat4.setText(tblMaterial.getModel().getValueAt(setar, 0).toString());
            txtPce4.setText(tblMaterial.getModel().getValueAt(setar, 1).toString());
        }else if (rbtn5.isSelected()){
            txtMat5.setText(tblMaterial.getModel().getValueAt(setar, 0).toString());
            txtPce5.setText(tblMaterial.getModel().getValueAt(setar, 1).toString());
        }
        
    }
    // Chamda para setar o campo de texto e as variaveis descrição e divisão
    private void cbDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDivisaoActionPerformed
        String divisao = (String) cbDivisao.getSelectedItem();
        if (divisao != null){
            switch (divisao) {
                case ("Explosivos (Comércio)"):
                   descricao = "Comércio em geral de fogos de artifício e assemelhados";
                   divi = "L-1";
                   ocupacaoEsp = "Comércio";
                   campoTexto();
                   break;
                case ("Explosivos (Indústria)"):
                    descricao = "Indústria de material explosivo";
                    divi = "L-2";
                    ocupacaoEsp = "Indústria";
                    campoTexto();
                    break;
                case ("Explosivos (Depósitos)"):
                    descricao = "Depósito de material explosivo";
                    divi = "L-3";
                    ocupacaoEsp = "Depósitos";
                    campoTexto();
                    break;
                case ("Especiais (Centrais de comunicação)"):
                    descricao = "Central telefônica, centros de comunicação,centrais de transmissão ou de distribuição de "
                            + "energia e assemelhados";
                    divi = "M-3";
                    ocupacaoEsp = "Especiais";
                    campoTexto();
                    break;
                case ("Especiais (Armazenamento e beneficiamento)"):
                    descricao = "Silos, armazéns de grãos e assemelhados";
                    divi = "M-5";
                    ocupacaoEsp = "Especiais";
                    campoTexto();
                    break;
                default:
                    break;
                    
                }
            }
            
        
    }//GEN-LAST:event_cbDivisaoActionPerformed

    // chamda do método de pesquisa
    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        pesquisar();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    // chamda do método setar
    private void tblMaterialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaterialMouseClicked
        try{
        if (rbtn1.isSelected()||rbtn2.isSelected()||rbtn3.isSelected()||rbtn4.isSelected()||rbtn5.isSelected()){
            setar();
        } else {
        JOptionPane.showMessageDialog(null,"Selecione a linha do material.");
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_tblMaterialMouseClicked

    // chamada do método calcular
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
             calcular();
             txtOcupacao.setText(getOcupacaoEsp());
             txtDivisao.setText(getDivi());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
            
            
        }

       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int confirma = JOptionPane.showConfirmDialog(null,"Deseja salvar e exportar para o projeto?", "Atenção", JOptionPane.YES_NO_OPTION);
       if (confirma == JOptionPane.YES_OPTION){
        try{ 
        getOcupacaoEsp();
        getDivi();
        getCargadeincendio();
        JOptionPane.showMessageDialog(null,"Dados exportados com sucesso! Na tela cálculo hidráulico clique em (Importar de Especiais)");
        this.dispose();
        } catch (Exception e){
           JOptionPane.showMessageDialog(null,e);
       }
       }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbDivisao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbtn1;
    private javax.swing.JRadioButton rbtn2;
    private javax.swing.JRadioButton rbtn3;
    private javax.swing.JRadioButton rbtn4;
    private javax.swing.JRadioButton rbtn5;
    private javax.swing.JTable tblMaterial;
    private javax.swing.JTextPane txpDescrcao;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCargaTotal;
    private javax.swing.JTextField txtDivisao;
    private javax.swing.JTextField txtMassa1;
    private javax.swing.JTextField txtMassa2;
    private javax.swing.JTextField txtMassa3;
    private javax.swing.JTextField txtMassa4;
    private javax.swing.JTextField txtMassa5;
    private javax.swing.JTextField txtMat1;
    private javax.swing.JTextField txtMat2;
    private javax.swing.JTextField txtMat3;
    private javax.swing.JTextField txtMat4;
    private javax.swing.JTextField txtMat5;
    private javax.swing.JTextField txtOcupacao;
    private javax.swing.JTextField txtPce1;
    private javax.swing.JTextField txtPce2;
    private javax.swing.JTextField txtPce3;
    private javax.swing.JTextField txtPce4;
    private javax.swing.JTextField txtPce5;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
